### ISSUE TITLE
Error Launch browser

### ISSUE THREAD

**Issue by meerpaluten** [Linus789/DeepLTranslator#4]
18:51:16 main                                          Main            ERROR  Error Translate " No Settings class was found" to Language de:
org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T20:55:26'
System info: host: 'ADMIN', ip: '169.254.127.214', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.7'
Driver info: driver.version: JBrowserDriver
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:136)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:340)
	at de.linus.deepltranslator.DeepLTranslatorBase.getTranslation(DeepLTranslatorBase.java:87)
	at de.linus.deepltranslator.DeepLTranslator.translate(DeepLTranslator.java:50)
	at de.linus.deepltranslator.DeepLTranslator.translate(DeepLTranslator.java:42)
	at xyz.custy.apis.messageapi.MessageAPI.lambda$copyDefaults$0(MessageAPI.java:59)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at xyz.custy.apis.messageapi.MessageAPI.copyDefaults(MessageAPI.java:53)
	at xyz.custy.apis.messageapi.MessageAPI.loadAndReload(MessageAPI.java:37)
	at xyz.custy.apis.messageapi.MessageAPI.<init>(MessageAPI.java:20)
	at xyz.custy.Main.<init>(Main.java:147)
	at xyz.custy.Main.main(Main.java:222)
Caused by: java.lang.IllegalStateException: Could not launch browser.
	... 11 more

**Comment by Linus789** [comment]
Use Java 8.
