### ISSUE TITLE
org.openqa.selenium.StaleElementReferenceException: The element no longer exists within the page.

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Linus789/DeepLTranslator#6]
Sometimes when translating I get the following exception:

```
org.openqa.selenium.StaleElementReferenceException: The element no longer exists within the page.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T20:55:26'
System info: host: 'DESKTOP-F8H276P', ip: '192.168.2.155', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:128)
	at com.machinepublishers.jbrowserdriver.Element.getAttribute(Element.java:184)
	at de.linus.deepltranslator.DeepLTranslatorBase.readResult(DeepLTranslatorBase.java:136)
	at de.linus.deepltranslator.DeepLTranslatorBase.getTranslation(DeepLTranslatorBase.java:106)
	at de.linus.deepltranslator.DeepLTranslator.translate(DeepLTranslator.java:50)
	at de.linus.deepltranslator.DeepLTranslator.translate(DeepLTranslator.java:42)
```
This causes an abort of the translation without retries. I'm not sure why it happens, maybe this can be handled better?
```
private String translate(String text, Language from, Language to, int repeated) throws Exception {
	try {
		return getTranslation(text, from, to);
	} catch (DeepLException e) {
		if(repeat(++repeated)) {
			Thread.sleep(getConfiguration().getRepetitionsDelay().apply(repeated).toMillis());
			return translate(text, from, to, repeated);
		}

		throw e;
	}
}
```

**Comment by Linus789** [comment]
This issue should be fixed with the newest release.

> This causes an abort of the translation without retries. I'm not sure why it happens, maybe this can be handled better?

The retries worked for me, but I re-implemented them nonetheless by making use of a for-loop.
